### ISSUE TITLE
Hi Masoudpz,

### ISSUE THREAD

**Issue by westamine** [rdevon/DIM#50]
Hi Dr,
I've cloned your repo and although i've cloned cortex-dev branch I get 
```
Could not find a version that satisfies the requirement cortex==0.13a0 (from cortex-DIM==0.13) (from versions: 0.1a0, 0.11)
No matching distribution found for cortex==0.13a0 (from cortex-DIM==0.13)
```
again.what is your idea?

_Originally posted by @masoudpz in https://github.com/rdevon/DIM/issues/14#issuecomment-512251509_

**Comment by rdevon** [comment]
Apologies, I gave up cortex on PIP a while ago. It can be installed via: https://github.com/rdevon/cortex

**Comment by yuu-Wang** [comment]
hi，how did you solve this problem？
(pytorch_2.2.1) root@wxy1:~/wangxy/DIM# python scripts/main.py --help
/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
warnings.warn(warning.format(ret))
Traceback (most recent call last):
File "scripts/main.py", line 12, in
from cortex_DIM.evaluation_models.classification_eval import ClassificationEval
ModuleNotFoundError: No module named 'cortex_DIM'

**Comment by yuu-Wang** [comment]
> Apologies, I gave up cortex on PIP a while ago. It can be installed via: https://github.com/rdevon/cortex

hi，how did you solve this problem？
(pytorch_2.2.1) root@wxy1:~/wangxy/DIM# python scripts/main.py --help
/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
warnings.warn(warning.format(ret))
Traceback (most recent call last):
File "scripts/main.py", line 12, in
from cortex_DIM.evaluation_models.classification_eval import ClassificationEval
ModuleNotFoundError: No module named 'cortex_DIM'

**Comment by yuu-Wang** [comment]
Did you run out? I need your help. Thank you!
